[package]
name = "simulate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# testbed
tokio = { version = "1.24.2", features = ["macros", "full"] }
revm = "3.0.0"

# price_simulation
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"
plotly = "0.8.3"
ethers-core = "1.0.2"
ethers-etherscan = "1.0.2"
eyre = "0.6.8"
